// Copyright © Clinton Ingram and Contributors.  Licensed under the MIT License.

// <auto-generated /> (not really, but this disables analyzer warnings)
// 
namespace ExternalDocumentation.Test;

/// <summary>enum referenced by enum, external project.</summary>
public enum EnumCrefEnumExternal
{
	/// <summary>D summary.</summary>
	D = 4,
}

/// <summary>class referenced by enum, external project.</summary>
public class EnumCrefClassExternal
{
	/// <summary>
	/// E summary
	/// </summary>
	public int E = 5;
}